apiVersion: apps/v1
kind: Deployment
metadata: { name: rabbitmq, namespace: app }
spec:
  replicas: 1
  selector: { matchLabels: { app: rabbitmq } }
  template:
    metadata: { labels: { app: rabbitmq } }
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672  # AMQP
            - containerPort: 15672 # UI
          env:
            - { name: RABBITMQ_DEFAULT_USER, value: user }
            - { name: RABBITMQ_DEFAULT_PASS, value: pass }
