# k8s/postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
type: Opaque
stringData:                       # хранится в base64 после apply
  POSTGRES_DB: pgres
  POSTGRES_USER: pgres
  POSTGRES_PASSWORD: pgres
